### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by JaysonDC030** [natenho/go-jira-migrate#3]
Hi, We have tried to run your tool, however it doesn't appear to work? following the instructions of download the binaries and run does nothing, could you please advise on what we should do? Or step by step process on how to use this?

**Comment by natenho** [comment]
Hello @JaysonDC030, please let me know which operating system are you using and let me know which error messages the tool is displaying, so we can try to figure out what is happening.

I was able to successfully migrate the projects of the company I currently work for a few months ago, that is why I decided to open source the tool.

**Comment by Nickelaer** [comment]
Hi Natenho,

I have tried the tool on a MacBook Air (M1).

For this I had downloaded and unpacked the following file:
go-jira-migrate_1.0.11_darwin_arm64.tar.gz

In my test I wanted to migrate a team-managed project, which is not yet present in the target instance. This resulted in the following message:
`2023/10/04 10:31:59 Create metadata not found for AM at target.atlassian.net, make sure the current user has access to create issues`

After that, I had also created a team-managed project in the target instance and wanted to migrate there, but the following message came up:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/natenho/go-jira-migrate/migration.getBoard(0x14000132000?, {0x16bd339e0, 0x2})
	/home/runner/work/go-jira-migrate/go-jira-migrate/migration/migrator.go:254 +0xf0
github.com/natenho/go-jira-migrate/migration.(*migrator).Execute(0x14000132000, {0x104307200, 0xe})
	/home/runner/work/go-jira-migrate/go-jira-migrate/migration/migrator.go:178 +0x134
main.main()
	/home/runner/work/go-jira-migrate/go-jira-migrate/main.go:93 +0x7a4
```
